### ISSUE TITLE
Gzip support vs Play builtin support

### ISSUE THREAD

**Issue by rvangsgaard** [edeustace/assets-loader#26]
What is the benefit of supporting gzip, as Play supports it with a global filter?

The Play filter support Accept-Encoding. If there is no benefit, I think it should be mentioned in the documentation, that it can be achieved using Play components: http://www.playframework.com/documentation/2.2.x/ScalaHttpFilters

Thank you for a great piece of software

**Comment by edeustace** [comment]
We gzip the transformed assets - I think that is still necessary.

I'd like to remove the custom controller - or use as much as from the standard play controller as possible, but I haven't got around to it.

Feel free to make a PR for the docs and/or controller changes.
