### ISSUE TITLE
Provided URLs do not consider application.context

### ISSUE THREAD

**Issue by davidcampos** [edeustace/assets-loader#27]
Hi,
I have specified the application.context in the application.conf file, so my app is available with a URL prefix.
However, the provided CSS and JS URLs do not consider it. Nevertheless, the files are available in the correct path.

For instance, considering application.context="context/":
Generated URL: https://localhost:9443/assets/stylesheets/xxxxx--1508627407.min.gz.css
Correct URL: https://localhost:9443/**context**/assets/stylesheets/xxxxx--1508627407.min.gz.css

I believe you should consider the application.context when generating the URLs.

Is that easy to fix? Can I help?
Cheers.

**Comment by edeustace** [comment]
Hi - I'll have a look later to see what the options are.

**Comment by edeustace** [comment]
@davidcampos - have a look at PR #28 - will that suffice?

**Comment by edeustace** [comment]
released in 12.2-SNAPSHOT

**Comment by edeustace** [comment]
Closing issue - will go in to 12.2
