### ISSUE TITLE
cloudfront

### ISSUE THREAD

**Issue by patrik7** [edeustace/assets-loader#29]
Hi,

We are using the tool and it's working great so far.

However, I am trying to route the assets thru CDN (cloudfront by amazon) and I can't find a way to do it.

In short, I need the generated URLs to use different domain.

For example, instead of:
/assets/style/app.css

I need:
//mmmmm.cloudfront.net/assets/style/app.css

It looks like master already has a solution, as AssetsInfo can be passed to Loader as parameter, but it is not released yet.

I also would like the use of CDN to be conditional (as i don't want it during dev).

Could you make the AssetsInfo use "def" (access methods) so they can be overriden, or suggest a differnt way to rout assets to other domain.

Thanks a lot

Regards
Patrik

**Comment by edeustace** [comment]
Hi @patrik7 - You'll want to use the Deployer trait, however in the rewrite that was done, I disabled it and forgot to add it back in. It needs to be added back in to the transfomration flow.

https://github.com/edeustace/assets-loader/blob/master/plugin/app/com/ee/assets/deployment/Deployer.scala#L14

https://github.com/edeustace/assets-loader/blob/master/plugin/app/com/ee/assets/Loader.scala#L45

I'll try and find some time to do so.

**Comment by patrik7** [comment]
I tried with the Deployer, I can modify the links that way, however, the actual assets are not generated (minification, ...)

I need to put CDN link on the website, but have the asset still available (accessible) using the former link.

**Comment by edeustace** [comment]
Oh - maybe it is back in the flow - Ok let me have a look later. Yes we can
make AssetsInfo a trait that may be overridden.

The conditional deploy - you should be able to use the conf for that.

https://github.com/edeustace/assets-loader#add-a-configuration-for-the-loader-either-in-the-main-conf-or-in-a-separate-file-that-is-included

**Comment by patrik7** [comment]
That's great, can't wait :)

**Comment by edeustace** [comment]
@patrik7 - I've published 12.2-SNAPSHOT within which AssetsInfo is a trait.

**Comment by edeustace** [comment]
Closing - haven't heard back - 12.2 is now released.

**Comment by patrik7** [comment]
It works, thanks!
