### ISSUE TITLE
Version hash - based on file names

### ISSUE THREAD

**Issue by patrik7** [edeustace/assets-loader#31]
Hi,

I noticed that after changing the content of javascripts the concatenated hash name did not change.

After digging thru code I found out the hash is not based on content, but the file names.

class CommonRootNamer(prefix: String, suffix: String) extends PathNamer {

  lazy val logger = Logger("common-root-namer")

  override def name[A](elements: Seq[Element[A]]): String = {
    import com.ee.utils.file.commonRootFolder

```
logger.trace(s"get common root for: ${elements.map(_.path)}")
val root = commonRootFolder(elements.map(_.path): _*)
logger.trace(s"commonRootFolder: $root")
val hash = elements.map(_.path).mkString(",").hashCode
val out = s"${root}/$prefix-$hash.$suffix"
logger.trace(s"out: $out")
out
```

  }
}

Am I reading this correctly? Is this desired? I would expect the hash to be based on the file(s) content.

**Comment by edeustace** [comment]
hi @patrik7 - the hash is based on the file name alright. I'm happy for this to change to a content based hash. Feel free to PR - otherwise I'll try and find some time at the weekend.

**Comment by patrik7** [comment]
Thanks a lot!
