### ISSUE TITLE
Setting closure compile options

### ISSUE THREAD

**Issue by larousso** [edeustace/assets-loader#9]
Hi, 

I'm currently using your project but I've got a problem on minification. I ve this king of errors : 
unknown:19: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
    restrict: 'EA',

Is possible to configure the closure compiler to set up the langage_in options ? 

Best regards, 
Alex

**Comment by edeustace** [comment]
Hi @larousso - I've updated the loader to take an Option[CompilerOptions] as the fourth argument. Its in version: `0.10.3-SNAPSHOT`.

**Comment by larousso** [comment]
Thanks a lot !

**Comment by edeustace** [comment]
Note: In versions: 10.3 or 11.1
